global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'users'
    static_configs:
      - targets: ['users:3001']

  - job_name: 'inventory'
    static_configs:
      - targets: ['inventory:3002']

  - job_name: 'orders'
    static_configs:
      - targets: ['orders:3003']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:3004']